<?php

return array(
    'login' => 'office/auth/login',
    'logout' => 'office/auth/logout',
    'office' => 'office/office/index',
    'requests' => 'office/request/index',
    'request/accept' => 'office/request/accept',
    'request/reject' => 'office/request/reject',
    'request/finish' => 'office/request/finish',
    'request/view' => 'office/request/view',
    'articles' => 'article/index',
    'article/view' => 'article/view',
    'article/create' => 'office/article/create',
    'article/edit' => 'office/article/edit',
    'article/draft' => 'office/article/draft',
    'article/verify' => 'admin/article/verify',
    'article/accept' => 'admin/article/accept',
    'article/reject' => 'admin/article/reject',
    'volunteers' => 'office/volunteer/index',
    'forum' => 'forum/forum/index',
    'forum/view' => 'forum/forum/view',
    'forum/topic' => 'forum/topic/view',
    'forum/create' => 'admin/forum/create',
    'forum/edit' => 'admin/forum/edit',
    'admin' => 'admin/moderation/index',
    'admin/users' => 'admin/user/index',
    'admin/articles' => 'admin/article/index',
    'admin/volunteers' => 'admin/volunteer/index',
    'admin/forums' => 'admin/forum/index',
);
